###Get Data
GET http://localhost:4004/odata/v4/customer/Customers

###Post 
POST http://localhost:4004/odata/v4/customer/Customers
Content-Type: application/json

{
    "name"        : "Revanth",
    "email"       : "revanth@gmail.com",
    "phone"       : 9876543210,
    "address"     : "Delhi",
    "totalOrders" : 50,
    "Status"      : 1,
    "orders" : [{
        "orderDate" : "2024-10-23",
        "orderStatus" : "Delivered",
        "quantity"    : 5,
        "netValue"    : 1500.00,
        "totalAmount" : 1600.00
    },{
        "orderDate" : "2024-10-23",
        "orderStatus" : "Not Delivered",
        "quantity"    : 2,
        "netValue"    : 500.00,
        "totalAmount" : 800.00
    }]
}
